name: docker-publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-hub-release:
    name: Release on Docker Hub
    needs:
      - release
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: relay-local
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            supabase/deno-relay:latest
            supabase/deno-relay:v${{ needs.release.outputs.version }}
